# Generated by Django 4.1.dev20220328112539 on 2022-04-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('globalScore', models.IntegerField()),
                ('timeFinish', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timePlayed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
